---
- name: Upload weekly kernel-clean crontab.
  template:
    src: cron/kernel-clean
    dest: /etc/cron.weekly/kernel-clean
    owner: root
    group: root
    mode: 0755
  notify:
    - restart cron

- name: Upload /etc/grub.d/02_force_timeout.
  template:
    src: grub.d/02_force_timeout
    dest: /etc/grub.d/02_force_timeout
    owner: root
    group: root
    mode: 0755
  failed_when: false

- name: Enable kernel logging to console.
  script: scripts/kernel_logging.sh creates=/kernel-logging-setup
  register: kernel_logging
  tags:
    - kernel_logging

- name: Update grub
  command: update-grub
  when: kernel_logging|changed
  tags:
    - kernel_logging

- name: Enable kernel modules to load at boot time.
  template:
    src: modules
    dest: /etc/modules
    owner: root
    group: root
    mode: 0644

- name: Enabling auto-fsck fix to prevent boot hangup.
  lineinfile:
    dest: /etc/default/rcS
    line: "FSCKFIX=yes"
    regexp: "FSCKFIX=no"
    # backrefs makes it so that if the regexp
    # isn't found the file is left unchanged
    backrefs: yes
    state: present
